version: "2"
run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    
    # Additional security & quality linters
    - bodyclose
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - nakedret
    - nestif
    - prealloc
    - revive
    - unconvert
    - unparam
    - wastedassign
