apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  # Environment
  ENVIRONMENT: "production"
  
  # API Gateway Configuration
  GATEWAY_HTTP_ADDR: ":8081"
  
  # Tracing Configuration
  JAEGER_ENDPOINT: "http://jaeger:14268/api/traces"
  
  # Database Configuration
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  
  # Message Broker Configuration
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  
  # Service Discovery
  TRIP_SERVICE_HOST: "trip-service"
  TRIP_SERVICE_PORT: "9093"
  DRIVER_SERVICE_HOST: "driver-service"  
  DRIVER_SERVICE_PORT: "9094"
  PAYMENT_SERVICE_HOST: "payment-service"
  PAYMENT_SERVICE_PORT: "9095"
  
  # Payment Configuration (Production URLs)
  STRIPE_SUCCESS_URL: "https://yourdomain.com/payment/success"
  STRIPE_CANCEL_URL: "https://yourdomain.com/payment/cancel"
  
  # External APIs (non-sensitive)
  OSRM_API: "https://router.project-osrm.org"
