apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: default
type: Opaque
data:
  # Base64 encoded values - replace with actual production values
  # echo -n "your_username" | base64
  username: cG9zdGdyZXM=
  # echo -n "your_password" | base64  
  password: cGFzc3dvcmQ=
  # echo -n "bolt_app" | base64
  database: Ym9sdF9hcHA=
  # echo -n "cloud-sql-proxy" | base64 (for GCP Cloud SQL)
  host: Y2xvdWQtc3FsLXByb3h5
---
apiVersion: v1
kind: Secret
metadata:
  name: external-apis
  namespace: default
type: Opaque
data:
  # Base64 encoded values - replace with actual production values
  # echo -n "sk_live_..." | base64
  stripe-key: c2tfbGl2ZV9jaGFuZ2VfbWU=
  # echo -n "https://router.project-osrm.org" | base64
  osrm: aHR0cHM6Ly9yb3V0ZXIucHJvamVjdC1vc3JtLm9yZw==
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: default
type: Opaque
data:
  # Base64 encoded values
  # echo -n "guest" | base64
  username: Z3Vlc3Q=
  # echo -n "guest" | base64
  password: Z3Vlc3Q=
