apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-service
  template:
    metadata:
      labels:
        app: driver-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9192"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: driver-service
          image: bolt-app/driver-service
          imagePullPolicy: Never
          ports:
            - containerPort: 9092
            - containerPort: 9192
              name: metrics
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: uri
            - name: JAEGER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: JAEGER_ENDPOINT
                  name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: driver-service
spec:
  type: ClusterIP
  ports:
    - port: 9092
      name: grpc
      targetPort: 9092
  selector:
    app: driver-service
