apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9194"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: payment-service
          image: bolt-app/payment-service
          imagePullPolicy: Never
          ports:
            - containerPort: 9004
            - containerPort: 9194
              name: metrics
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: JAEGER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: JAEGER_ENDPOINT
                  name: app-config
            - name: STRIPE_SUCCESS_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: STRIPE_SUCCESS_URL
            - name: STRIPE_CANCEL_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: STRIPE_CANCEL_URL

            # Stripe credentials
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secrets
                  key: stripe-secret-key

            # RabbitMQ credentials
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: uri
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - port: 9004
      name: grpc
      targetPort: 9004
  type: ClusterIP
