apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
stringData:
  username: "guest"
  password: "guest"
  uri: "amqp://guest:guest@rabbitmq:5672/"

---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secrets
type: Opaque
stringData:
  stripe-webhook-key: "your-stripe-webhook-key-here"
  stripe-secret-key: "your-stripe-secret-key-here"
  stripe-publishable-key: "your-stripe-publishable-key-here"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  host: "postgres"
  port: "5432"
  database: "bolt_app"
  username: "postgres"
  password: "password"

---
apiVersion: v1
kind: Secret
metadata:
  name: external-apis
type: Opaque
stringData:
  osrm: "http://router.project-osrm.org"